version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    build: .
    expose:
      - "3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha
    depends_on:
      - db
    networks:
      - backend

  nginx:
    image: nginx:1.25-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - app
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
