#version: '3.8'

services:
  db:
    image: postgres:15-alpine
    cpus: 0.8
    mem_limit: 1610m
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rinha
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    tmpfs:
      - /var/lib/postgresql/data:rw,noexec,nosuid,size=100m
    networks:
      - backend
    command: >
      postgres
        -c max_connections=100
        -c shared_buffers=512MB
        -c logging_collector=off
        -c log_min_messages=fatal

  api1:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile.amd}
    image: rinha-api:local
    cpus: 0.35
    mem_limit: 640m
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha
    depends_on:
      - db
    networks:
      - backend
    sysctls:
      net.core.somaxconn: 65535
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  api2:
    image: rinha-api:local
    cpus: 0.35
    mem_limit: 512m
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/rinha
    depends_on:
      - db
      - api1
    networks:
      - backend
    sysctls:
      net.core.somaxconn: 65535
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  nginx:
    image: nginx:1.25-alpine
    cpus: 0.05
    mem_limit: 256m
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    depends_on:
      - api1
      - api2
    networks:
      - backend

networks:
  backend:
    driver: bridge
